<?php

namespace OpsuHcmBundle\EntityRepository;

use Doctrine\ORM\EntityRepository;

/**
 * Persona
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Persona extends EntityRepository
{
	

	public function listaMunicipios($idEstado)
	{
 			
 			 $entities=$this->getEntityManager()->createQuery("
            SELECT municipio
            FROM OpsuHcmBundle:Municipio municipio
            LEFT JOIN municipio.estado estado
            WHERE estado.id = :estado_id
        ")->setParameter('estado_id', $idEstado);

  			return $entities->getArrayResult();
	}

	public function listaParroquias($idMunicipio)
	{
 			
 			$entities=$this->getEntityManager()->createQuery("
            SELECT parroquia
            FROM OpsuHcmBundle:Parroquia parroquia
            LEFT JOIN parroquia.municipio idMunicipio
            WHERE idMunicipio.id = :municipio_id
        ")->setParameter('municipio_id', $idMunicipio);

  			return $entities->getArrayResult();
	}

}
