<?php

namespace OpsuHcmBundle\EntityRepository;

use Doctrine\ORM\EntityRepository;

/**
 * Solicitud
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Solicitud extends EntityRepository
{
}
