services:
#    opsu_hcm.example:
#        class: OpsuHcmBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.form.type.persona:
         class: OpsuHcmBundle\Form\PersonaType
         arguments: ["@security.context"]
         tags:
             - { name: form.type, alias: user_type }