<?php

namespace OpsuHcmBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CasosAsignadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasosAsignadoRepository extends EntityRepository
{
}
