<?php

namespace OpsuHcmBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonaUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaUserRepository extends EntityRepository
{
}
