<?php

namespace OpsuHcmBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReembolsoSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReembolsoSolicitudRepository extends EntityRepository
{
}
