<?php

namespace OpsuHcmBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SaimeCedulasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaimeCedulasRepository extends EntityRepository
{
}
